<?php

namespace rajmundtoth0\AuditDriver\Types;

/**
 * @phpstan-type BulkParams array{
 *     index?: string,
 *     wait_for_active_shards?: string,
 *     refresh?: string,
 *     routing?: string,
 *     timeout?: int|string,
 *     _source?: string|array<string>,
 *     _source_excludes?: string|array<string>,
 *     _source_includes?: string|array<string>,
 *     pipeline?: string,
 *     require_alias?: bool,
 *     require_data_stream?: bool,
 *     list_executed_pipelines?: bool,
 *     pretty?: bool,
 *     human?: bool,
 *     error_trace?: bool,
 *     source?: string,
 *     filter_path?: string|array<string>,
 *     body: string|array<mixed>,
 * }
 * @phpstan-type IndexParams array{
 *     index: string,
 *     wait_for_active_shards?: string,
 *     timeout?: int|string,
 *     master_timeout?: int|string,
 *     pretty?: bool,
 *     human?: bool,
 *     error_trace?: bool,
 *     source?: string,
 *     filter_path?: string|array<string>,
 *     body?: string|array<mixed>,
 * }
 * @phpstan-type IndexTemplateParams array{
 *     name: string,
 *     create?: bool,
 *     cause?: string,
 *     master_timeout?: int|string,
 *     pretty?: bool,
 *     human?: bool,
 *     error_trace?: bool,
 *     source?: string,
 *     filter_path?: string|array<string>,
 *     body: string|array<mixed>,
 * }
 * @phpstan-type DeleteParams array{
 *     id: string,
 *     index: string,
 *     wait_for_active_shards?: string,
 *     refresh?: string,
 *     routing?: string,
 *     timeout?: int|string,
 *     if_seq_no?: int,
 *     if_primary_term?: int,
 *     version?: int,
 *     version_type?: string,
 *     pretty?: bool,
 *     human?: bool,
 *     error_trace?: bool,
 *     source?: string,
 *     filter_path?: string|array<string>,
 * }
 * @phpstan-type DeleteByQueryParams array{
 *     index: array<string>|string,
 *     analyzer?: string,
 *     analyze_wildcard?: bool,
 *     default_operator?: string,
 *     df?: string,
 *     from?: int,
 *     ignore_unavailable?: bool,
 *     allow_no_indices?: bool,
 *     conflicts?: string,
 *     expand_wildcards?: string,
 *     lenient?: bool,
 *     preference?: string,
 *     q?: string,
 *     routing?: array<string>|string,
 *     scroll?: int|string,
 *     search_type?: string,
 *     search_timeout?: int|string,
 *     max_docs?: int,
 *     sort?: array<string>|string,
 *     terminate_after?: int,
 *     stats?: array<string>|string,
 *     version?: bool,
 *     request_cache?: bool,
 *     refresh?: bool,
 *     timeout?: int|string,
 *     wait_for_active_shards?: string,
 *     scroll_size?: int,
 *     wait_for_completion?: bool,
 *     requests_per_second?: int,
 *     slices?: int|string,
 *     pretty?: bool,
 *     human?: bool,
 *     error_trace?: bool,
 *     source?: string,
 *     filter_path?: array<string>|string,
 *     body: array<mixed>|string,
 * }
 * @phpstan-type PutLifecycleParams array{
 *     policy: string,
 *     master_timeout?: int|string,
 *     timeout?: int|string,
 *     pretty?: bool,
 *     human?: bool,
 *     error_trace?: bool,
 *     source?: string,
 *     filter_path?: array<string>|string,
 *     body?: array<mixed>|string,
 * }
 *
 * @phpstan-type SearchParams array{
 *     index?: string|array<string>,
 *     analyzer?: string,
 *     analyze_wildcard?: bool,
 *     ccs_minimize_roundtrips?: bool,
 *     default_operator?: string,
 *     df?: string,
 *     explain?: bool,
 *     stored_fields?: string|array<string>,
 *     docvalue_fields?: string|array<string>,
 *     from?: int,
 *     force_synthetic_source?: bool,
 *     ignore_unavailable?: bool,
 *     ignore_throttled?: bool,
 *     allow_no_indices?: bool,
 *     expand_wildcards?: string,
 *     lenient?: bool,
 *     preference?: string,
 *     q?: string,
 *     routing?: string|array<string>,
 *     scroll?: int|string,
 *     search_type?: string,
 *     size?: int,
 *     sort?: string|array<string>,
 *     _source?: string|array<string>,
 *     _source_excludes?: string|array<string>,
 *     _source_includes?: string|array<string>,
 *     terminate_after?: int,
 *     stats?: string|array<string>,
 *     suggest_field?: string,
 *     suggest_mode?: string,
 *     suggest_size?: int,
 *     suggest_text?: string,
 *     timeout?: int|string,
 *     track_scores?: bool,
 *     track_total_hits?: bool|int,
 *     allow_partial_search_results?: bool,
 *     typed_keys?: bool,
 *     version?: bool,
 *     seq_no_primary_term?: bool,
 *     request_cache?: bool,
 *     batched_reduce_size?: int,
 *     max_concurrent_shard_requests?: int,
 *     pre_filter_shard_size?: int,
 *     rest_total_hits_as_int?: bool,
 *     min_compatible_shard_node?: string,
 *     include_named_queries_score?: bool,
 *     pretty?: bool,
 *     human?: bool,
 *     error_trace?: bool,
 *     source?: string,
 *     filter_path?: string|array<string>,
 *     body?: string|array<mixed>,
 * }
 *
 * @phpstan-type CountParams array{
 *     index?: string|array<string>,
 *     ignore_unavailable?: bool,
 *     ignore_throttled?: bool,
 *     allow_no_indices?: bool,
 *     expand_wildcards?: string,
 *     min_score?: int,
 *     preference?: string,
 *     routing?: string|array<string>,
 *     q?: string,
 *     analyzer?: string,
 *     analyze_wildcard?: bool,
 *     default_operator?: string,
 *     df?: string,
 *     lenient?: bool,
 *     terminate_after?: int,
 *     pretty?: bool,
 *     human?: bool,
 *     error_trace?: bool,
 *     source?: string,
 *     filter_path?: string|array<string>,
 *     body?: string|array<mixed>,
 * }
 */
final class ElasticsearchTypes
{
}
